# Generated by Django 6.0.4 on 2026-05-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_geojsonupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedTechnicalMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_epsg', models.CharField(blank=True, max_length=50)),
                ('bbox_minx', models.FloatField(blank=True, null=True)),
                ('bbox_miny', models.FloatField(blank=True, null=True)),
                ('bbox_maxx', models.FloatField(blank=True, null=True)),
                ('bbox_maxy', models.FloatField(blank=True, null=True)),
                ('geometry_type', models.CharField(blank=True, max_length=50)),
                ('feature_count', models.IntegerField(blank=True, null=True)),
                ('attribute_schema', models.JSONField(default=list, help_text='Array of {name, dtype} objects')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_metadata', to='projects.geojsonupload')),
            ],
        ),
    ]
