# Generated by Django 6.0.4 on 2026-05-02 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
        ('projects', '0002_geojsonupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stac_version', models.CharField(default='1.0.0', max_length=10)),
                ('stac_item_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list, help_text='Stored as array of strings')),
                ('datetime_start', models.DateTimeField(blank=True, null=True)),
                ('datetime_end', models.DateTimeField(blank=True, null=True)),
                ('license', models.CharField(blank=True, choices=[('CC-BY-4.0', 'CC-BY-4.0 (Attribution)'), ('CC-BY-SA-4.0', 'CC-BY-SA-4.0 (Attribution-ShareAlike)'), ('CC0-1.0', 'CC0-1.0 (Public Domain)'), ('OGL-Australia', 'OGL Australia (Open Government Licence)'), ('proprietary', 'Proprietary'), ('other', 'Other')], max_length=50)),
                ('providers', models.JSONField(default=list, help_text='Array of STAC provider objects')),
                ('links', models.JSONField(default=list, help_text='Array of STAC link objects')),
                ('full_stac_json', models.JSONField(blank=True, help_text='Final assembled STAC Item', null=True)),
                ('ai_suggestions_applied', models.BooleanField(default=False)),
                ('export_count', models.IntegerField(default=0)),
                ('last_exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_record', to='projects.geojsonupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
