# Generated by Django 6.0.4 on 2026-04-29 13:42

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJSONUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=projects.models.geojson_upload_path)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='projects.geodataproject')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
